# Generated by Django 5.2.5 on 2025-08-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_review_comment_en_review_comment_ky_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(choices=[('Bishkek', 'Bishkek'), ('Talas', 'Talas'), ('Jalal_Abad', 'Jalal_Abad'), ('Osh', 'Osh'), ('Batken', 'Batken'), ('Kara_Kol', 'Kara_Kol'), ('Naryn', 'Naryn')], max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'apartment'), ('house', 'house'), ('commercial_property', 'commercial_property'), ('room', 'room'), ('land_plot_or_lot', 'land_plot_or_lot'), ('summer_house_or_country house', 'summer_house_or_country house'), ('parking_space_or_garage', 'parking_space_or_garage')]),
        ),
        migrations.AlterField(
            model_name='property',
            name='region',
            field=models.CharField(choices=[('Chui', 'Chui'), ('Talas', 'Talas'), ('Jalal_Abad', 'Jalal_Abad'), ('Osh', 'Osh'), ('Batken', 'Batken'), ('Ysyk_Kol', 'Ysyk_Kol'), ('Naryn', 'Naryn')], max_length=20),
        ),
    ]
