# Generated by Django 5.2.5 on 2025-08-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_property_city_alter_property_property_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'apartment'), ('house', 'house'), ('commercial_property', 'commercial_property'), ('room', 'room'), ('land_plot_or_lot', 'land_plot_or_lot'), ('summer_house_or_country_house', 'summer_house_or_country_house'), ('parking_space_or_garage', 'parking_space_or_garage')]),
        ),
    ]
